### ISSUE TITLE
error occur in every page

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#108]
``` javascript
VM284 extensions::uncaught_exception_handler:8Error 
in event handler for (unknown): 
TypeError: Cannot read property 'https://www.google.com' of undefined

    at checkBlackList (chrome-extension://...../content_scripts/content_scripts.js:381:24)
    at chrome-extension://...../content_scripts/top.js:53:9
    at chrome-extension://...../content_scripts/runtime.js:22:13
```

**Comment by brookhong** [comment]
What version of Surfingkeys are you using?

The code from backtrace seems to be out-dated.
