### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by smic1909** [brookhong/Surfingkeys#746]
Visiting https://www.ruhrnachrichten.de and checking the console output, the following appears:

```
Uncaught DOMException: Blocked a frame with origin "https://www.ruhrnachrichten.de" from accessing a cross-origin frame.
    at Function.o.init (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:1:18856)
    at HTMLIFrameElement.<anonymous> (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:1:19240)```

**Comment by adrian-gierakowski** [comment]
getting a similar error on `inbox.google.com`, which stops Surfingkeys from working on that page

it used to work for me some time ago

some stackoverflow questions which might provide answers:

https://stackoverflow.com/questions/37001541/cross-origin-chrome-extension
https://stackoverflow.com/questions/51813745/uncaught-domexception-blocked-a-frame-with-origin-chrome-extension
