### ISSUE TITLE
点击Disable Surfingkeys无反应

### ISSUE THREAD

**Issue by seasonxuan** [brookhong/Surfingkeys#76]
从 https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc 这里安装的扩展。 安装成功后，打开这个github项目页面， 点击Disable Surfingkeys 无反应。试过其他页面，也是无反应。其他功能正常。
```
Surfingkeys 0.5.4
Chromium 48.0.2564.109 (开发者内部版本) （64 位）
操作系统	Windows 
JavaScript  V8 4.8.271.19
```
控制台报出一个错误
```
[unexpected runtime message] {"target":"content_runtime","subject":"getBlacklist"}
VM46 extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Events.toggleBlacklist is not a function
    at Object.runtime.runtime_handlers.toggleBlacklist (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/top.js:1:2703)
    at chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:3:27890handler @ VM46 extensions::uncaught_exception_handler:8(anonymous function) @ VM46 extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ VM45 extensions::event_bindings:376EventImpl.dispatch @ VM45 extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ VM51 extensions::utils:94messageListener @ VM53 extensions::messaging:179target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ VM45 extensions::event_bindings:387target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ VM51 extensions::utils:94EventImpl.dispatch_ @ VM45 extensions::event_bindings:371EventImpl.dispatch @ VM45 extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ VM51 extensions::utils:94dispatchOnMessage @ VM53 extensions::messaging:310
common_content.min.js:3 [unexpected runtime message] {"target":"content_runtime","origin":".*","subject":"toggleBlacklist"}
```

**Comment by seasonxuan** [comment]
而用`Alt+S`可以正常切换Surfingkeys

**Comment by brookhong** [comment]
谢谢，是个bug。

**Comment by brookhong** [comment]
Released in 0.5.5.
