### ISSUE TITLE
Throws error on every page load: TypeError: Cannot read property 'blur' of null

### ISSUE THREAD

**Issue by tconroy** [brookhong/Surfingkeys#81]
Hi!
Loving SurfingKeys, but every page load throws the following error:

```
Error in event handler for (unknown): TypeError: Cannot read property 'blur' of null
    at Object.t.enter (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:3:29357)
    at HTMLDocument.e (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:4:18091)
    at l (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:2:6665)
    at Object.add [as done] (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:2:6974)
    at Z.fn.ready (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:2:9080)
    at Object.t.resetMode (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:4:18908)
    at HTMLDocument.<anonymous> (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/content_scripts.js:1:5605)
    at HTMLDocument.dispatch (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:2:17673)
    at HTMLDocument.g.handle (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:2:14448)
    at Object.trigger (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js:2:16783)handler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:377EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151dispatchOnMessage @ extensions::messaging:336
```

any idea how to fix? system is latest Chrome stable, OSX 10.11.4.

**Comment by brookhong** [comment]
I can not reproduce this issue though, I refined some code in 0.5.7.

Please try 0.5.7, and see if the issue was gone.

**Comment by tconroy** [comment]
@brookhong thanks, I'll give it a shot today. I did notice it started showing when I began development on a mobile web project which makes heavy usage of Hammer.js, intercepting touch/focus/blur events. So maybe that has something to do with it.

Thanks again for a great extension, btw! I've tried numerous VIM-like keybindings for Chrome and this one is by far the best. 👍
